import foliations_differential_topology_geometric_theory_theorem_canonical_lane_mathlib.GateLemmas
import foliations_differential_topology_geometric_theory_theorem_canonical_lane_mathlib.FinalTheorem
