import foliations_differential_topology_geometric_theory_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace foliations_differential_topology_geometric_theory_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end foliations_differential_topology_geometric_theory_theorem_canonical_lane_mathlib
end HautevilleHouse
